# Generated by Django 4.2.26 on 2025-11-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbearia_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cortes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="cortes/"),
                ),
            ],
        ),
    ]
