# Generated by Django 5.2.8 on 2025-11-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barbearia_admin", "0002_cortes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cortes",
        ),
    ]
