# Generated by Django 5.2.8 on 2026-01-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbearia_admin", "0003_delete_cortes"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="email",
            field=models.EmailField(default="sem-email@temporario.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="data",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="horario",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
