# Generated by Django 5.2.8 on 2026-01-31 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbearia_admin", "0004_agendamento_email_alter_agendamento_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamento",
            name="email",
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="data",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="horario",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="nome",
            field=models.CharField(max_length=120),
        ),
    ]
