# Generated by Django 5.2.8 on 2026-02-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "barbearia_admin",
            "0005_remove_agendamento_email_alter_agendamento_data_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="horario",
            field=models.TimeField(),
        ),
    ]
