# Generated by Django 5.2.8 on 2025-11-25 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="corte",
            name="tempo_estimado",
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
