# Generated by Django 5.2.8 on 2025-11-25 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes_admin", "0002_corte_tempo_estimado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="barbas/"),
                ),
                (
                    "tempo_estimado",
                    models.DurationField(default=datetime.timedelta(seconds=1200)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pintura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="pinturas/"),
                ),
                (
                    "tempo_estimado",
                    models.DurationField(default=datetime.timedelta(seconds=2700)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sobrancelha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="sobrancelhas/"),
                ),
                (
                    "tempo_estimado",
                    models.DurationField(default=datetime.timedelta(seconds=900)),
                ),
            ],
        ),
    ]
