# Generated by Django 5.2.8 on 2025-12-01 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes_admin", "0003_barba_pintura_sobrancelha"),
    ]

    operations = [
        migrations.CreateModel(
            name="designs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="designs/"),
                ),
                (
                    "tempo_estimado",
                    models.DurationField(default=datetime.timedelta(seconds=1500)),
                ),
            ],
        ),
        migrations.AddField(
            model_name="barba",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="corte",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pintura",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sobrancelha",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
