# Generated by Django 5.2.8 on 2025-12-02 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes_admin", "0004_designs_barba_descricao_corte_descricao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="servicos/"),
                ),
                (
                    "tempo_estimado",
                    models.DurationField(default=datetime.timedelta(seconds=1800)),
                ),
                (
                    "categorias",
                    models.CharField(
                        choices=[
                            ("Corte", "Corte"),
                            ("Barba", "Barba"),
                            ("Sobrancelha", "Sobrancelha"),
                            ("Pintura", "Pintura"),
                            ("Designs", "Designs"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
    ]
