# Generated by Django 5.2.8 on 2025-12-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes_admin", "0005_servico_delete_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="servico",
            name="categorias",
        ),
        migrations.AddField(
            model_name="servico",
            name="categorias",
            field=models.ManyToManyField(
                related_name="servicos", to="clientes_admin.categoria"
            ),
        ),
    ]
