# Generated by Django 5.2.8 on 2025-12-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes_admin", "0006_categoria_remove_servico_categorias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="categorias/"),
        ),
    ]
