# Generated by Django 5.2.8 on 2025-12-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes_admin", "0007_categoria_foto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Barba",
        ),
        migrations.DeleteModel(
            name="Corte",
        ),
        migrations.DeleteModel(
            name="designs",
        ),
        migrations.DeleteModel(
            name="Pintura",
        ),
        migrations.DeleteModel(
            name="Sobrancelha",
        ),
    ]
