# Generated by Django 4.2.26 on 2025-11-19 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("telefone", models.CharField(max_length=20)),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("horario", models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Disponibilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("horario", models.TimeField()),
                ("disponivel", models.BooleanField(default=True)),
            ],
        ),
    ]
