# Generated by Django 4.2.26 on 2025-11-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="agendamento",
            unique_together={("data", "horario")},
        ),
    ]
